name: spring-ci

on:
  pull_request:
    branches:
      - "dev"
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up .csv files
        run: |
          echo "${{ secrets.CAMPUS_DATASET }}" | base64 --decode > ./campus_dataset.csv
          echo "${{ secrets.TERMS_INFO }}" | base64 --decode > ./terms_dataset.csv
        shell: bash

      - name: Set up AWS Credentials
        run: |
          mkdir -p ~/.aws
          echo "${{ secrets.AWS_CREDENTIALS }}" | base64 --decode > ~/.aws/credentials
        shell: bash

      - name: Set up application.yml file
        run: |
          mkdir -p src/main/resources
          mkdir -p src/test/resources
          echo "${{ secrets.APPLICATION_YML }}" > src/main/resources/application.yml
          echo "${{ secrets.APPLICATION_TEST_YML }}" > src/test/resources/application.yml
        shell: bash

      - name: Grant Execute Permission for gradlew
        run: |
          chmod +x gradlew
        shell: bash

      - name: Build gradle
        run: |
          ./gradlew clean build
        shell: bash
